---@class RunContext
---@field file string
---@field pos_id string
---@field type neotest.PositionType
---@field handler TestFrameworkHandler

---@class TestFrameworkHandler
---@field default_modules string[] Default list of qualified modules used to determine if this handler can be used.
---@field position_query string Tree-sitter query for test and namespace positions.
---@field parse_positions fun(file_path:string):neotest.Tree Function that parses the positions in a test file.
---@field get_cabal_test_opts fun(pos:neotest.Position):string[] Function that constructs the options for a cabal test command.
---@field get_stack_test_opts fun(pos:neotest.Position):string[] Function that constructs the options for a stack test command.
---@field parse_results (fun(context:RunContext, out_path:string, tree:neotest.Tree): table<string, neotest.Result>)|nil Function for parsing the test results.
